spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
    initialization-mode: always
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always

logging:
  config: classpath:log4j2-local.xml
